### ISSUE TITLE
Baking a generator using parts of UNIREST

### ISSUE THREAD

**Issue by Goutte** [brandonlamb/godot-unirest#9]
I started [baking **generator templates** for GDScript](https://github.com/OpenAPITools/openapi-generator/issues/13719) (Godot 4), and I'm considering using the code from here (Response, Request, etc.) into the template.

I'll probably copy/paste and tweak for Godot 4.  _(no addon dependency graph)_

Is that OK ?  (libre software all around)

> I'm only noticing unirest now, otherwise I would have started with it

**Comment by brandonlamb** [comment]
Oh yea, i dont care lol. I havent been doing any game dev for 1-2 years already, take what you want haha
